# Generated by Django 3.2.9 on 2021-11-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticate', '0002_auto_20211130_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticate.cargos'),
            preserve_default=False,
        ),
    ]
